export const icons = {
  bell: { title: "Bell", size: "h-6 w-6" },
  "bell-fill": { title: "Bell", size: "h-6 w-6" },
  "bell-slash": { title: "Muted bell", size: "h-6 w-6" },
  bookmark: { title: "Bookmark", size: "h-6 w-6" },
  "bookmark-fill": { title: "Bookmark", size: "h-6 w-6" },
  check: { title: "Checkmark", size: "h-3 w-3" },
  chevron: { title: "Chevron", size: "h-6 w-6" },
  copy: { title: "Copy", size: "h-5 w-5" },
  clock: { title: "Clock", size: "h-6 w-6" },
  "clock-fill": { title: "Clock", size: "h-6 w-6" },
  "desktop-device": { title: "Desktop device", size: "h-6 w-6" },
  "eye": { title: "Show", size: "h-6 w-6" },
  "eye-slash": { title: "Hide", size: "h-6 w-6" },
  "fork-knife": { title: "Fork and knife", size: "h-6 w-6" },
  gear: { title: "Settings", size: "h-6 w-6" },
  home: { title: "Home", size: "h-6 w-6" },
  "home-fill": { title: "Home", size: "h-6 w-6" },
  key: { title: "Key", size: "h-6 w-6" },
  lightbulb: { title: "Lightbulb", size: "h-6 w-6" },
  link: { title: "Link", size: "h-6 w-6" },
  "link-external": { title: "External link", size: "h-6 w-6" },
  "logo-github": { title: "GitHub logo", size: "h-4 w-11" },
  mail: { title: "Mail", size: "h-6 w-6" },
  "mark-github": { title: "GitHub mark", size: "h-6 w-6" },
  moon: { title: "Dark theme", size: "h-6 w-6" },
  "organization": { title: "Organization", size: "h-6 w-6" },
  "people": { title: "People", size: "h-6 w-6" },
  "person": { title: "Person", size: "h-6 w-6" },
  "person-add": { title: "Add person", size: "h-6 w-6" },
  "person-fill": { title: "Person", size: "h-6 w-6" },
  "sidebar-collapse": { title: "Collapse sidebar", size: "h-6 w-6" },
  "sidebar-expand": { title: "Expand sidebar", size: "h-6 w-6" },
  "sign-in": { title: "Sign in", size: "h-6 w-6" },
  "sign-out": { title: "Sign out", size: "h-6 w-6" },
  "smiley": { title: "Smiley", size: "h-6 w-6" },
  sun: { title: "Light theme", size: "h-6 w-6" },
  "thumbsdown": { title: "Thumbs down", size: "h-6 w-6" },
  "thumbsup": { title: "Thumbs up", size: "h-6 w-6" },
  trash: { title: "Trash", size: "h-6 w-6" },
} as const satisfies Record<string, { title: string; size: string }>;

export type IconName = keyof typeof icons;
