export const icons = {
  alert: { title: "Alert", size: "h-6 w-6" },
  brain: { title: "Brain", size: "h-6 w-6" },
  "calendar-days": { title: "Calendar", size: "h-6 w-6" },
  camera: { title: "Camera", size: "h-6 w-6" },
  chart: { title: "Chart", size: "h-6 w-6" },
  "circle-check": { title: "Completed", size: "h-6 w-6" },
  cloud: { title: "Cloud", size: "h-6 w-6" },
  database: { title: "Database", size: "h-6 w-6" },
  flask: { title: "Flask", size: "h-6 w-6" },
  hash: { title: "Number", size: "h-6 w-6" },
  heart: { title: "Heart", size: "h-6 w-6" },
  info: { title: "Information", size: "h-6 w-6" },
  "list-ordered": { title: "Ordered list", size: "h-6 w-6" },
  percent: { title: "Percent", size: "h-6 w-6" },
  "shield-off": { title: "Shield disabled", size: "h-6 w-6" },
  stethoscope: { title: "Stethoscope", size: "h-6 w-6" },
  sync: { title: "Sync", size: "h-6 w-6" },
  "trend-down": { title: "Trend down", size: "h-6 w-6" },
  "trend-up": { title: "Trend up", size: "h-6 w-6" },
  "wifi-off": { title: "Wi-Fi disconnected", size: "h-6 w-6" },
  x: { title: "Close", size: "h-3 w-3" },
  bell: { title: "Bell", size: "h-6 w-6" },
  "bell-fill": { title: "Bell", size: "h-6 w-6" },
  "bell-slash": { title: "Muted bell", size: "h-6 w-6" },
  "book-open": { title: "Open book", size: "h-6 w-6" },
  bookmark: { title: "Bookmark", size: "h-6 w-6" },
  "bookmark-fill": { title: "Bookmark", size: "h-6 w-6" },
  cgm: { title: "Continuous glucose monitor", size: "h-6 w-6" },
  check: { title: "Checkmark", size: "h-3 w-3" },
  "chat-bubbles": { title: "Chat bubbles", size: "h-6 w-6" },
  chevron: { title: "Chevron", size: "h-6 w-6" },
  "circle-slash": { title: "Circle slash", size: "h-6 w-6" },
  "sleep-zzz": { title: "Sleep", size: "h-6 w-6" },
  copy: { title: "Copy", size: "h-5 w-5" },
  clock: { title: "Clock", size: "h-6 w-6" },
  "clock-fill": { title: "Clock", size: "h-6 w-6" },
  "desktop-device": { title: "Desktop device", size: "h-6 w-6" },
  "exercise-dumbbell": { title: "Exercise", size: "h-6 w-6" },
  eye: { title: "Show", size: "h-6 w-6" },
  "eye-slash": { title: "Hide", size: "h-6 w-6" },
  "fork-knife": { title: "Fork and knife", size: "h-6 w-6" },
  gear: { title: "Settings", size: "h-6 w-6" },
  glucose: { title: "Glucose indicator", size: "h-10 w-10" },
  "lumose-logo-icon": { title: "Lumose logo", size: "h-10 w-10" },
  "logo-text": { title: "Lumose wordmark", size: "h-auto w-[135px]" },
  home: { title: "Home", size: "h-6 w-6" },
  "home-fill": { title: "Home", size: "h-6 w-6" },
  "insulin-pump": { title: "Insulin pump", size: "h-6 w-6" },
  key: { title: "Key", size: "h-6 w-6" },
  lightbulb: { title: "Lightbulb", size: "h-6 w-6" },
  link: { title: "Link", size: "h-6 w-6" },
  "link-external": { title: "External link", size: "h-6 w-6" },
  "logo-github": { title: "GitHub logo", size: "h-4 w-11" },
  "logo-lumose-icon": { title: "Lumose logo", size: "h-10 w-10" },
  "logo-lumose-icon-text": { title: "Lumose", size: "h-auto w-52" },
  "logo-lumose-text": { title: "Lumose", size: "h-auto w-52" },
  "logo-lumose-text-icon": { title: "Lumose", size: "h-auto w-52" },
  mail: { title: "Mail", size: "h-6 w-6" },
  "mark-github": { title: "GitHub mark", size: "h-6 w-6" },
  menu: { title: "Menu", size: "h-6 w-6" },
  moon: { title: "Dark theme", size: "h-6 w-6" },
  organization: { title: "Organization", size: "h-6 w-6" },
  people: { title: "People", size: "h-6 w-6" },
  person: { title: "Person", size: "h-6 w-6" },
  "person-add": { title: "Add person", size: "h-6 w-6" },
  "person-fill": { title: "Person", size: "h-6 w-6" },
  share: { title: "Share", size: "h-5 w-[1.125rem]" },
  "sidebar-collapse": { title: "Collapse sidebar", size: "h-6 w-6" },
  "sidebar-expand": { title: "Expand sidebar", size: "h-6 w-6" },
  "sign-in": { title: "Sign in", size: "h-6 w-6" },
  "sign-out": { title: "Sign out", size: "h-6 w-6" },
  smiley: { title: "Smiley", size: "h-6 w-6" },
  sun: { title: "Light theme", size: "h-6 w-6" },
  syringe: { title: "Syringe", size: "h-6 w-6" },
  thumbsdown: { title: "Thumbs down", size: "h-6 w-6" },
  thumbsup: { title: "Thumbs up", size: "h-6 w-6" },
  trash: { title: "Trash", size: "h-6 w-6" },
  "zoom-in": { title: "Zoom in", size: "h-4 w-4" },
  "zoom-out": { title: "Zoom out", size: "h-4 w-4" },
} as const satisfies Record<string, { title: string; size: string }>;

export type IconName = keyof typeof icons;
