package com.glycemicgpt.mobile.wear

import com.glycemicgpt.mobile.BuildConfig
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File
import java.security.MessageDigest
import java.util.zip.ZipFile

class WatchFacePusherTest {

    @Test
    fun `Result Success contains status and optional slotId`() {
        val result = WatchFacePusher.Result.Success(status = "installed", slotId = "slot-1")
        assertEquals("installed", result.status)
        assertEquals("slot-1", result.slotId)
    }

    @Test
    fun `Result Success allows null slotId`() {
        val result = WatchFacePusher.Result.Success(status = "sent", slotId = null)
        assertEquals("sent", result.status)
        assertEquals(null, result.slotId)
    }

    @Test
    fun `Result Error contains message`() {
        val result = WatchFacePusher.Result.Error("No watch connected")
        assertEquals("No watch connected", result.message)
    }

    @Test
    fun `Result sealed class covers all cases`() {
        val success: WatchFacePusher.Result = WatchFacePusher.Result.Success("ok", null)
        val error: WatchFacePusher.Result = WatchFacePusher.Result.Error("fail")
        assertTrue(success is WatchFacePusher.Result.Success)
        assertTrue(error is WatchFacePusher.Result.Error)
    }

    // ------------------------------------------------------------------
    // Watch face asset drift gate (GLY-160).
    //
    // Every phone build bundles pre-built WFF APKs from
    // app/src/<buildType>/assets. These are committed artifacts generated by
    // `./gradlew -Pandroid.enableResourceOptimizations=false
    // :watchface:updateAppWatchFaceAssets` from the templates in
    // watchface/src/<flavor>/templates/watchface.xml. Nothing rebuilds them
    // automatically, so this gate fails CI whenever a template (or the
    // committed APK) changes without the other being regenerated, whenever a
    // provider package does not match the buildType's wear-device package, or
    // whenever the digital face loses one of its five complication slots.
    //
    // The gate reads content OUT of the committed APKs only. It must never
    // rebuild-and-compare: the strip/re-sign step in :watchface is
    // non-reproducible and unsigned on CI.
    // ------------------------------------------------------------------

    private data class CommittedAsset(
        val flavor: String,
        val buildType: String,
        val wearPackage: String,
        val expectedSlotIds: Set<Int>,
    ) {
        val assetPath = "src/$buildType/assets/glycemicgpt-watchface-$flavor.apk"
        val templatePath = "src/$flavor/templates/watchface.xml"
    }

    private val committedAssets = listOf(
        CommittedAsset("digitalFull", "debug", "com.glycemicgpt.mobile.debug", setOf(0, 1, 2, 3, 4)),
        CommittedAsset("digitalFull", "release", "com.glycemicgpt.mobile", setOf(0, 1, 2, 3, 4)),
        CommittedAsset("analogMechanical", "debug", "com.glycemicgpt.mobile.debug", setOf(0, 1, 2)),
        CommittedAsset("analogMechanical", "release", "com.glycemicgpt.mobile", setOf(0, 1, 2)),
    )

    @Test
    fun `committed assets embed the template with buildType provider substitution`() {
        committedAssets.forEach { asset ->
            val embedded = embeddedWatchFaceXml(asset)
            val template = File(watchfaceModuleDir(), asset.templatePath)
            assertTrue("Missing watch face template: $template", template.isFile)
            val templateText = template.readText()
            assertTrue(
                "${asset.templatePath} must carry the $WEAR_PKG_TOKEN provider token",
                templateText.contains(WEAR_PKG_TOKEN),
            )
            val expected = templateText.replace(WEAR_PKG_TOKEN, asset.wearPackage)
            assertEquals(
                "${asset.assetPath} is out of lockstep with ${asset.templatePath}. " +
                    "Regenerate with: ./gradlew -Pandroid.enableResourceOptimizations=false " +
                    ":watchface:updateAppWatchFaceAssets",
                normalizeLineEndings(expected),
                normalizeLineEndings(embedded),
            )
        }
    }

    @Test
    fun `digitalFull assets expose all five complication slots including Alerts and AI Chat`() {
        committedAssets.forEach { asset ->
            val embedded = embeddedWatchFaceXml(asset)
            assertEquals(
                "${asset.assetPath} has the wrong complication slot set",
                asset.expectedSlotIds,
                slotIds(embedded),
            )
        }
        committedAssets.filter { it.flavor == "digitalFull" }.forEach { asset ->
            val providers = primaryProviders(embeddedWatchFaceXml(asset))
            listOf("AlertsComplicationDataSource", "ChatComplicationDataSource").forEach { source ->
                assertTrue(
                    "${asset.assetPath} lost its $source complication",
                    providers.any { it.endsWith(".$source") },
                )
            }
        }
    }

    @Test
    fun `complication providers target the wear-device package for the asset buildType`() {
        committedAssets.forEach { asset ->
            val embedded = embeddedWatchFaceXml(asset)
            val providers = primaryProviders(embedded)
            assertEquals(
                "${asset.assetPath} must declare one provider per slot",
                asset.expectedSlotIds.size,
                providers.size,
            )
            providers.forEach { provider ->
                assertTrue(
                    "${asset.assetPath} provider '$provider' does not target " +
                        "${asset.wearPackage}/com.glycemicgpt.weardevice.complications.*",
                    provider.startsWith("${asset.wearPackage}/com.glycemicgpt.weardevice.complications."),
                )
            }
        }
    }

    @Test
    fun `release assets never reference the debug wear package`() {
        committedAssets.filter { it.buildType == "release" }.forEach { asset ->
            assertFalse(
                "${asset.assetPath} contains a '.debug' reference; a release face " +
                    "pointing complications at the debug wear app renders dead slots " +
                    "on a fresh production install",
                embeddedWatchFaceXml(asset).contains(".debug"),
            )
        }
    }

    @Test
    fun `BuildConfig watch face hashes are in lockstep with the committed debug assets`() {
        // Unit tests compile against the debug BuildConfig, so this pins the
        // debug pair; the release pair is produced by the same Gradle helper.
        val expected = mapOf(
            "digitalFull" to BuildConfig.WATCHFACE_DIGITAL_SHA256,
            "analogMechanical" to BuildConfig.WATCHFACE_ANALOG_SHA256,
        )
        committedAssets.filter { it.buildType == "debug" }.forEach { asset ->
            assertEquals(
                "BuildConfig hash for ${asset.assetPath} is stale",
                expected.getValue(asset.flavor),
                sha256(assetFile(asset)),
            )
        }
    }

    private fun embeddedWatchFaceXml(asset: CommittedAsset): String {
        val apk = assetFile(asset)
        return ZipFile(apk).use { zip ->
            val entry = requireNotNull(zip.getEntry(EMBEDDED_XML_PATH)) {
                "${asset.assetPath} has no $EMBEDDED_XML_PATH entry. It was " +
                    "likely rebuilt with resource-path optimization enabled; " +
                    "regenerate with: ./gradlew " +
                    "-Pandroid.enableResourceOptimizations=false " +
                    ":watchface:updateAppWatchFaceAssets"
            }
            zip.getInputStream(entry).use { it.readBytes().toString(Charsets.UTF_8) }
        }
    }

    private fun assetFile(asset: CommittedAsset): File {
        val file = File(appModuleDir(), asset.assetPath)
        assertTrue("Missing committed watch face asset: $file", file.isFile)
        return file
    }

    /** Locates the app module directory regardless of the test runner's CWD. */
    private fun appModuleDir(): File {
        val marker = "src/main/java/com/glycemicgpt/mobile/wear/WatchFacePusher.kt"
        var dir: File? = File(System.getProperty("user.dir")).absoluteFile
        while (dir != null) {
            listOf(dir, File(dir, "app"), File(dir, "apps/mobile/app")).forEach { candidate ->
                if (File(candidate, marker).isFile) return candidate
            }
            dir = dir.parentFile
        }
        fail("Could not locate the app module from ${System.getProperty("user.dir")}")
        throw AssertionError("unreachable")
    }

    private fun watchfaceModuleDir(): File = File(appModuleDir().parentFile, "watchface")

    private fun slotIds(xml: String): Set<Int> =
        Regex("slotId=\"(\\d+)\"").findAll(xml).map { it.groupValues[1].toInt() }.toSet()

    private fun primaryProviders(xml: String): List<String> =
        Regex("primaryProvider=\"([^\"]+)\"").findAll(xml).map { it.groupValues[1] }.toList()

    private fun normalizeLineEndings(text: String): String = text.replace("\r\n", "\n")

    private fun sha256(file: File): String =
        MessageDigest.getInstance("SHA-256")
            .digest(file.readBytes())
            .joinToString("") { "%02x".format(it) }

    private companion object {
        const val EMBEDDED_XML_PATH = "res/raw/watchface.xml"
        const val WEAR_PKG_TOKEN = "@WEAR_PKG@"
    }
}
